# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

# Events, when any event happen, we can trigger a workflow
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

# jobs get run when any event triggers, groups a set of actions that will be executed
jobs:
  build:

    runs-on: ubuntu-latest
    # actions to perform
    steps:
    # 1
    - uses: actions/checkout@v2
    # 2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
    # specifying java version
      with:
        java-version: 1.8
    # run attribute we use for running any command like any linux command or any other command we use run attribute
    - name: Grant execute permission for gradle
      run: chmod +x gradlew

    - name: Build with gradle
      run: ./gradlew build
